Completed 5 test cases
vantruongt2/PySelenium pull request #7
Opened 2019-05-07 10:04 UTC by trungtranjj

Completed these test cases:
DA_LOGIN_TC001
DA_LOGIN_TC002
DA_LOGIN_TC003
DA_MP_TC021
DA_MP_TC022

2019-05-08 02:57 UTC, trungtranjj commented
Attach the report files

[test-output.zip](https://github.com/vantruongt2/PySelenium/files/3155266/test-output.zip)

2019-05-08 03:37 UTC, vantruongt2 requested changes

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/testcases/da_login_tests/da_login_tc001_test.py
> +    da_general = DAGeneralPage()
Remove unused variable

2019-05-08 03:37 UTC, vantruongt2 commented on selenpy/element/text_box.py
> +    @property
Remove it

2019-05-08 03:37 UTC, vantruongt2 commented on selenpy/element/text_box.py
> +        self._input.clear()
use `self.find_element().clear()`

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/pages/general_page.py
> +            menu_item = BaseElement("//a[text()='%s']")
Should define it as class variable

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/pages/general_page.py
> +        if parent != None:
is not None

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/testcases/da_mp/da_mp_test.py
> +        assert "{0} already exists. Please enter a different name.".format(
Kind of messages, put all of them into one file. Easy to manage

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/testcases/da_mp/da_mp_test.py
> +            "{0}>{1}".format(self.page_3, self.page_4))
Should have common method to do that. Like `get_menu_item`

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/utils/common.py
> +    browser.get_driver().execute_script("arguments[0].setAttribute('style', 'outline-style: solid; outline-color: red; outline-width: medium;')", WebElement)
Should have another class to handle all of behaviors of browser. like browser_helper or something like that

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/utils/common.py
> +def high_light_element(WebElement):
Wrong naming for argument `WebElement` should be `element `or `web_element`. And the type of argument should be BaseElement

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/utils/constants.py
> +DA_URL = "http://localhost:55000/TADashboard/login.jsp"
Should have a way to update this variable in real-time. When I need to run all of tests on other URL. What should I do?

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/utils/common.py
> +    return now.strftime(constants.DATE_FORMAT)
Don't hard format here. When I need to get today in other format, I need to create new one?

2019-05-08 03:37 UTC, vantruongt2 commented on tests_trung/pages/general_page.py
> +        "xpath=//div[@id='main-menu']//a[text()='Overview']")
For xpath, don't need to put prefix

2019-05-08 03:37 UTC, vantruongt2 commented on selenpy/support/factory.py
> +    current = "default"
Missing new line

2019-05-08 03:39 UTC, vantruongt2 requested changes

2019-05-08 03:39 UTC, vantruongt2 commented on tests_trung/testcases/da_mp/da_mp_test.py
> +        self.manager_page.delete_page()
Should delete page by name instead of calling 2 methods select page and then delete page. 
`self.manager_page.delete_page(self.test_page)`

2019-05-09 03:04 UTC, vophi027 commented on tests_trung/pages/dashboard_page.py
> +        self._mmu_global_setting.wait_for_visible(constants.WAIT_SHORT)
why you don't use the default timeout?

2019-05-09 03:04 UTC, vophi027 commented on tests_trung/pages/dashboard_page.py
> +        self._lbl_new_page_title.wait_for_invisible()
should add the successed parameter with default value = True

2019-05-09 03:04 UTC, vophi027 commented on tests_trung/pages/dashboard_page.py
> +        self._lbl_new_page_title.wait_for_invisible()
same as above

2019-05-09 03:06 UTC, vophi027 commented on tests_trung/controls/menu.py
> +                self._mmu_item.move_to()
add new line

2019-05-09 04:07 UTC, vantruongt2 requested changes

2019-05-09 04:07 UTC, vantruongt2 commented on tests_trung/pages/dashboard_page.py
> +        self._lbl_new_page_title.wait_for_invisible()
It doesn't work when creating the invalid page

2019-05-09 09:00 UTC, merged